name: CD

on:
  push:
    branches:
      - 'master'

env:
  NODE_VERSION: '16'

jobs:
  release:
    name: 'Release Please'
    runs-on: ubuntu-latest

    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3
        id: release-please
        with:
          command: manifest
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json

      - name: Release Please Output
        run: echo '${{ toJSON(steps.release-please.outputs) }}'

      - name: Setup vars
        if: steps.release-please.outputs.releases_created != 'true' && steps.release-please.outputs.pr
        id: vars
        run: |
          echo ::set-output name=commit_subject::"${{ fromJSON(steps.release-please.outputs.pr).title }}"
          echo ::set-output name=git_branch::"${{ fromJSON(steps.release-please.outputs.pr).headBranchName }}"

      - name: Fetching Release Please's branch
        if: steps.release-please.outputs.releases_created != 'true' && steps.release-please.outputs.pr
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.vars.outputs.git_branch }}
          fetch-depth: 2

      - uses: actions/setup-node@v2
        if: steps.release-please.outputs.releases_created != 'true' && steps.release-please.outputs.pr
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Updating package-lock.json file
        if: steps.release-please.outputs.releases_created != 'true' && steps.release-please.outputs.pr
        run: npm install --no-audit --no-fund --ignore-scripts --package-lock-only

      - name: Merging changes with last commit
        if: steps.release-please.outputs.releases_created != 'true' && steps.release-please.outputs.pr
        run: |
          git reset --soft HEAD~1
          git add .

      - name: Commit & Push changes
        if: steps.release-please.outputs.releases_created != 'true' && steps.release-please.outputs.pr
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: '${{ steps.vars.outputs.commit_subject }}'
          branch: '${{ steps.vars.outputs.git_branch }}'
          force: true

  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    needs: [release]

    if: needs.release.outputs.release_created

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: ${{env.NODE_VERSION}}
          registry-url: 'https://registry.npmjs.org'

      - name: Cache Node Modules
        id: cache-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ env.NODE_VERSION }}-${{ runner.OS }}-build-${{ hashFiles('package-lock.json') }}

      - name: Install
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm install

      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
